Basic Docs setup
MaineKuehn/change-log pull request #4
Opened 2019-11-08 01:37 UTC by maxfischer2781

This pull request adds basic documentation. Changes include:

* [ ] basic sphinx docs,
* [ ] automatic readthedocs builds.

2019-11-08 01:37 UTC, pep8speaks commented
Hello @maxfischer2781! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`docs/conf.py`](https://github.com/MaineKuehn/change-log/blob/0b6b264ad0ca32a53581cfd2b1fe700f03fa9b2b/docs/conf.py):

> [Line 52:31](https://github.com/MaineKuehn/change-log/blob/0b6b264ad0ca32a53581cfd2b1fe700f03fa9b2b/docs/conf.py#L52): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2019-11-11 13:01 UTC, eileen-kuehn requested changes
Great thing, we should consider having something like this in a project template :)

However, I left some minor comments you should have a look at before merging.

2019-11-11 13:01 UTC, eileen-kuehn commented on docs/conf.py
> +author = 'Eileen Kuehn, Max Fischer'
If you exchange those two lines you can even include the ``author`` into the copyright ;)

2019-11-11 13:01 UTC, eileen-kuehn commented on docs/subtool/log.rst
> +Each fragment file contains a mappings that must contain
```suggestion
Each fragment file contains a mapping that must contain
```

2019-11-11 13:01 UTC, eileen-kuehn commented on docs/subtool/log.rst
> +    # any of 'added', 'changed', 'fixed', 'deprecated', 'removed', 'security'
Please consider to put these options into the description text not just the example code.

2019-11-11 13:01 UTC, eileen-kuehn commented on docs/subtool/log.rst
> +      forbidden, and strings are escaped in field values, tags, and measurements.
What do you think about using an example that does match this repository? For example you could include this PR itself. So if anybody tries to interpret this also finds the referenced PR and so on.

2019-11-11 13:01 UTC, eileen-kuehn commented on docs/subtool/log.rst
> +The ``version`` is optional and in most cases does not need manual definitions.
```suggestion
The ``version`` is optional and in most cases does not need manual definition.
```

2019-11-11 13:01 UTC, eileen-kuehn commented on docs/subtool/log.rst
> +Unversioned fragments belong to the "next" release, and
```suggestion
Unversioned fragments belong to the *next* release, and
```

2019-11-11 15:15 UTC, maxfischer2781 commented on docs/subtool/log.rst
> +      forbidden, and strings are escaped in field values, tags, and measurements.
I think that's a great idea!

2019-11-11 15:36 UTC, maxfischer2781 commented on docs/subtool/log.rst
> +    # any of 'added', 'changed', 'fixed', 'deprecated', 'removed', 'security'
Documented the expected choices for ``category``.

2019-11-11 15:36 UTC, maxfischer2781 commented on docs/subtool/log.rst
> +      forbidden, and strings are escaped in field values, tags, and measurements.
Now using this PR and a new issue #5 as example.

2019-11-11 15:36 UTC, maxfischer2781 commented on docs/conf.py
> +author = 'Eileen Kuehn, Max Fischer'
Dome.

2019-11-12 10:26 UTC, eileen-kuehn approved these changes
Great, especially the self-reference 👍

2019-11-12 14:21 UTC, merged